language: node_js
node_js:
  - "latest"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key: HEROKU_API_KEY
  local_dir: build
  on:
    branch: master
